#!/usr/bin/env python3
"""Generate Scala `.scl` and `.kbm` fixtures.

Tuning code needs a handful of scales that exercise different things, and
writing them by hand is both tedious and where the mistakes go. These are the
ones worth having:

    12edo          every step size is a period, so period inference must pick
                   the octave out of {100 c, 200 c, …, 1200 c, …}
    13ed3          Bohlen-Pierce: an equal division of something that is *not*
                   an octave, so no candidate is one
    9ed3over2      an equal division of 3/2, where the period is not even a
                   whole-number ratio and is not recoverable from frequencies
    7edo + kbm     a mapping that leaves keys unmapped, so `x` gets exercised

    python3 scales.py --list
    python3 scales.py 12edo                       # to stdout
    python3 scales.py --all --out ./fixtures      # every fixture, as files
    python3 scales.py edo --steps 19              # any equal division
    python3 scales.py kbm --unmapped              # a mapping with holes

`.kbm` files named `<prefix>_<i>.kbm` are, by this project's convention, the
mapping for MIDI channel *i*; one without a suffix is the default for every
channel that has none. That is not part of the Scala format — see
../references/scala.md and the tuning page's docs.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def edo(steps: int, period_cents: float = 1200.0, description: str = "") -> str:
    """`steps` equal divisions of `period_cents`."""
    if not description:
        ratio = "2/1" if abs(period_cents - 1200.0) < 1e-6 else f"{period_cents:.4f} c"
        description = f"{steps} equal divisions of {ratio}"

    lines = ["! generated by scales.py", "!", description, f" {steps}", "!"]

    # A Scala scale lists the intervals *above* the root, and its **last tone is
    # the period** — which is why a file-based tuning states its period rather
    # than having it inferred.
    for i in range(1, steps + 1):
        lines.append(f" {i * period_cents / steps:.5f}")

    return "\n".join(lines) + "\n"


def just(ratios: list[str], description: str = "A just scale") -> str:
    """A scale of exact ratios, written as fractions — which Scala distinguishes
    from cents by the presence of a `/`."""
    lines = ["! generated by scales.py", "!", description, f" {len(ratios)}", "!"]
    lines += [f" {r}" for r in ratios]
    return "\n".join(lines) + "\n"


def kbm(size: int = 12, first: int = 0, last: int = 127, middle: int = 60,
        reference: int = 69, frequency: float = 440.0,
        octave: int | None = None, unmapped: bool = False) -> str:
    """A keyboard mapping.

    With `unmapped`, the black keys are written as `x` — the Scala spelling for
    "this key sounds nothing". A receiver must keep that distinct from "this key
    is tuned to 0 Hz", which is why a tuning table wants an optional per note.
    """
    if octave is None:
        octave = size

    lines = [
        "! generated by scales.py",
        f"{size}",          # size of map
        f"{first}",         # first MIDI note to retune
        f"{last}",          # last
        f"{middle}",        # middle note, where the map starts
        f"{reference}",     # reference note
        f"{frequency}",     # its frequency
        f"{octave}",        # scale degree that formal octave falls on
        "!",
    ]

    if unmapped:
        # C D E F G A B mapped, the five black keys left out.
        lines += ["0", "x", "2", "x", "4", "5", "x", "7", "x", "9", "x", "11"]
    else:
        lines += [str(i) for i in range(size)]

    return "\n".join(lines) + "\n"


FIXTURES = {
    "12edo": (
        "12edo.scl",
        lambda: edo(12, 1200.0, "Twelve equal divisions of the octave"),
        "every step is a period; inference must still pick 1200 c",
    ),
    "13ed3": (
        "13ed3.scl",
        lambda: edo(13, 1200.0 * 1.5849625007211562, "Bohlen-Pierce: 13 equal divisions of 3/1"),
        "an equal division of a tritave — no candidate is an octave",
    ),
    "9ed3over2": (
        "9ed3over2.scl",
        lambda: edo(9, 701.9550008653874, "Nine equal divisions of 3/2"),
        "period is not a whole-number ratio, so it is unrecoverable",
    ),
    "7edo": (
        "7edo.scl",
        lambda: edo(7, 1200.0, "Seven equal divisions of the octave"),
        "pairs with the unmapped .kbm below",
    ),
    "7edo-kbm": (
        "7edo.kbm",
        lambda: kbm(12, unmapped=True),
        "a mapping leaving the black keys unmapped ('x')",
    ),
    "7edo-kbm-2": (
        "7edo_2.kbm",
        lambda: kbm(12, unmapped=True),
        "the same, named for channel 2 by the _i convention",
    ),
    "ji5": (
        "ji5.scl",
        lambda: just(["9/8", "5/4", "3/2", "5/3", "2/1"], "Five-limit just, five tones"),
        "exact ratios rather than cents",
    ),
}


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("fixture", nargs="?", default="--list")
    p.add_argument("--list", action="store_true")
    p.add_argument("--all", action="store_true", help="write every fixture")
    p.add_argument("--out", type=Path, help="directory to write into (default: stdout)")
    p.add_argument("--steps", type=int, default=12)
    p.add_argument("--period", type=float, default=1200.0)
    p.add_argument("--unmapped", action="store_true")

    args = p.parse_args()

    if args.list or (args.fixture == "--list" and not args.all):
        for name, (filename, _, note) in FIXTURES.items():
            print(f"  {name:<12} {filename:<16} {note}")
        print("\n  edo          --steps N [--period CENTS]")
        print("  kbm          [--unmapped]")
        return 0

    def emit(filename: str, text: str) -> None:
        if args.out:
            args.out.mkdir(parents=True, exist_ok=True)
            (args.out / filename).write_text(text)
            print(f"wrote {args.out / filename}")
        else:
            sys.stdout.write(text)

    if args.all:
        for filename, build, _ in FIXTURES.values():
            emit(filename, build())
        return 0

    if args.fixture == "edo":
        emit(f"{args.steps}edo.scl", edo(args.steps, args.period))
    elif args.fixture == "kbm":
        emit("generated.kbm", kbm(unmapped=args.unmapped))
    elif args.fixture in FIXTURES:
        filename, build, _ = FIXTURES[args.fixture]
        emit(filename, build())
    else:
        print(f"unknown fixture '{args.fixture}' (try --list)", file=sys.stderr)
        return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
